# Pruebas Triage - Sintomas

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import os
import sys

# Ruta a la raíz del proyecto
ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
if ROOT not in sys.path:
    sys.path.append(ROOT)

from utils.input_data.triage_symptoms import *
from utils.general_utils import text_cleaning
from utils.input_data.providers_utils import (
    merge_provider_locations,
    clean_providers_data,
)

from utils.matching_utils.recommendation_engine import build_triage_correspondence_table

2025-12-04 21:20:39.478 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-04 21:20:39.480 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-04 21:20:39.480 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
/opt/homebrew/Caskroom/miniconda/base/envs/maestria/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/opt/homebrew/Caskroom/miniconda/base/envs/maestria/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-12-04 21:20:42.196 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-04 21:20:42.197 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-04 21:20:42.196 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-04 21:20:42.197 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [14]:
data = pd.read_excel("../data/triage_sintomas.xlsx")
data

,Semaforización,Hombre,Mujer,Edad,Enf laboral,AT 1ra vez,AT control,Categoría,Indícanos con cuál de los siguientes síntomas te identificas:,Modificador: ¿El síntoma que presentas está asociado con algún otro de los siguientes síntomas o características?,Modalidad,Temporalidad,Asegurador,Triage,CIE 10 asociado,Nivel de complejidad,Accidente de tránsito,Especialidad urgencias,Especialidad 2,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,X,"Boca, garganta y cuello",Golpe o trauma en la boca,Ninguno de los anteriores,Presencial,Prioritaria,NaN,T4,S005,NaN,NaN,Odontología,NaT,NaT
1,NaN,NaN,NaN,NaN,NaN,X,NaN,"Boca, garganta y cuello",Golpe o trauma en la boca,Lesión de encía o mucosas orales,Presencial,Prioritaria,NaN,T4,S005,NaN,NaN,NaN,NaT,NaT
2,NaN,NaN,NaN,NaN,NaN,X,X,"Boca, garganta y cuello",Golpe o trauma en la boca,Cambio de color evidente en un diente luego de...,Urgencias,T3,NaN,T3,S005,NaN,NaN,Odontología,NaT,NaT
3,NaN,NaN,NaN,NaN,NaN,X,NaN,"Boca, garganta y cuello",Golpe o trauma en la boca,Asociado a dolor y deformidad en boca o mandíbula,Urgencias,T3,NaN,T3,S005,NaN,NaN,NaN,NaT,NaT
4,NaN,NaN,NaN,NaN,NaN,X,NaN,"Boca, garganta y cuello",Golpe o trauma en la boca,Fractura evidente del tejido dental,Urgencias,T3,NaN,T3,S005,NaN,NaN,Odontología,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Traige 3,Urgencias,NaN,NaN,NaN,NaT,NaT
380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Traige 4,Prioritaria,NaN,NaN,NaN,NaT,NaT
381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Triage 5,Programada,NaN,NaN,NaN,NaT,NaT
382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT

In [15]:
data_sintomas = load_sintomas_from_excel("../data/triage_sintomas.xlsx")

In [16]:
data_sintomas

{'Boca, garganta y cuello': {'Golpe o trauma en la boca': ['Ninguno de los anteriores',
   'Lesión de encía o mucosas orales',
   'Cambio de color evidente en un diente luego del trauma',
   'Asociado a dolor y deformidad en boca o mandíbula',
   'Fractura evidente del tejido dental',
   'Desplazamiento o aflojamiento del diente por el trauma',
   'Asociado a inflamación, sangrado o secreción purulenta en boca, dientes o encías',
   'Pérdida o caída del diente'],
  'Dificultad para tragar (ej: se me atora la comida)': ['Asociado a trauma o quemadura en el lugar de trabajo']},
 'Génitourinario ': {'Trauma genital': ['Ninguno de los anteriores',
   'Asociado a sangrado o herida abierta en genitales ',
   'Amputación o aplastamiento de genitales',
   'Dolor intenso o deformidad en la zona afectada',
   'Asociado a fiebre, calor, enrojecimiento, hinchazón o dolor en genitales posterior al accidente de trabajo',
   'Dificultad o molestia para orinar posterior al accidente de trabajo',
   'Imposibilidad para orinar posterior al accidente de trabajo (retención de orina)'],
  'Sensación de masas o abultamiento en región genital posterior a un trauma': ['Ninguno de los anteriores'],
  'Sensación de masas o abultamiento en región genital': ['Asociado a dolor intenso o cambios en la coloración de la piel'],
  'Secreción de pus por genitales o ano': ['Posterior a procedimiento debido a tu accidente de trabajo o enfermedad laboral',
   'Posterior a un trauma',
   'Asociado a fiebre, sudoración, decaimiento o debilidad para pararse Posterior a procedimiento debido a tu accidente de trabajo o enfermedad laboral'],
  'Orina con sangre posterior a un trauma': ['Ninguno de los anteriores'],
  'Orina con sangre': ['Fiebre (temperatura mayor a 38° grados medidas por termómetro) debido a procedimiento por evento laboral',
   'Dolor abdominal fuerte o cólico intenso debido a procedimiento por evento laboral',
   'Fue producto de un trauma reciente asociado a accidente de trabajo',
   'Posterior a cirugía reciente (menor a una semana) relacionado a evento laboral',
   'Dolor en los costados o debajo de la región costo-vertebral debido a procedimiento por evento laboral']},
 'Ginecológico': {'Secreción o sangrado del pezón': ['Ninguno de los anteriores',
   'Asociado a trauma ',
   'Asociado a dolor, inflamación, enrojecimiento o calor en la mama'],
  'Dolor en senos o mama': ['Ninguno de los anteriores',
   'Asociado a trauma ',
   'Asociado a dolor, inflamación, enrojecimiento o calor en la mama'],
  'Sangrado vaginal': ['Ninguno de los anteriores',
   'Trauma en zona genital',
   'Asociado a signos como: sudoración, piel pálida o debilidad para pararse',
   'Sangrado abundante o hemorragia que no se detiene'],
  'Flujo vaginal': ['Ninguno de los anteriores',
   'Posterior a trauma, procedimiento o cirugía reciente asociado a un accidente de trabajo o enfermedad laboral',
   'Dolor pélvico asociado o no con fiebre (temperatura mayor a 38° grados medidas por termómetro)'],
  'Trauma en mama, pecho o tórax': ['Ninguno de los anteriores',
   'Asociado a deformidad o cambio en el aspecto de la mama',
   'Asociado a dolor, enrojecimiento, calor, secreción o fiebre'],
  'Dolor pélvico o dolor bajito': ['Ninguno de los anteriores',
   'Posterior a trauma, procedimiento o cirugía reciente por accidente de trabajo o enfermedad laboral']},
 'Nariz': {'Alteración del olfato': ['Ninguno de los anteriores',
   'Asociado a trauma, golpe o caída en el trabajo',
   'Exposición de sustancias química o irritantes en el trabajo',
   'Asociado a asma, rinitis o alergias',
   'Posterior a cirugía o procedimiento reciente en cara'],
  'Congestión nasal': ['Ninguno de los anteriores',
   'Asociado a trauma, golpe o caída en el trabajo',
   'Exposición de sustancias química o irritantes en el trabajo',
   'Asociado a asma, rinitis o alergias',
   'Posterior a cirugía o procedimiento reciente en cara'],
  'Cuerpo extraño en nariz': ['Sin modificador'],
  'Sangrado nasal': ['Ninguno de los anteriores',
   'Exposición de sustancias química o irritantes en el trabajo',
   'Posterior a cirugía o procedimiento reciente en cara',
   'Asociado a trauma, golpe o caída en el trabajo',
   'En la actualidad te encuentras tomando medicamentos anticoagulantes como: warfarina, apixabán, ribaroxabán, dabigatrán, edoxabán, heparina, clopidogrel o aspirina'],
  'Herida o trauma en nariz': ['Ninguno de los anteriores',
   'Raspón o herida superficial que presentó sangrado escaso',
   'Trauma asociado a nariz tapada que dificultad respirar',
   'Asociado a herida con sangrado que no se detiene o deformidad nasal'],
  'Deformidad nasal': ['Ninguno de los anteriores',
   'Posterior a procedimiento debido a tu accidente de trabajo',
   'Asociado a trauma, golpe o caída en el trabajo']},
 'Neurológico o cabeza': {'Dolor de cabeza': ['Ninguno de los anteriores',
   'Asociado a altos niveles de ruido o tensión muscular en tu lugar de trabajo',
   'Asociado a uso de auriculares de forma constante en tu lugar de trabajo',
   'Asociado a trauma, golpe o caída en el trabajo',
   'Posterior a procedimiento debido a tu accidente de trabajo o enfermedad laboral',
   'Alteraciones en el estado mental, visuales, sensitivas, del habla, lenguaje o motoras.',
   'Entumecimiento de la cara o el cuerpo posterior a cirugía realizada en los últimos 20 días'],
  'Pérdida completa de la movilidad en extremidades (parálisis)': ['Sin modificador'],
  'Parálisis facial o en la cara (ej: boca torcida u ojo cerrado)': ['Sin modificador'],
  'Mareo o vértigo (ej: sensación de movimiento propio o de los objetos)': ['Ninguno de los anteriores',
   'Asociado a cambios de temperatura en el trabajo',
   'Asociado sonido fuerte, vibración o trabajos de altura o acuáticos',
   'Posterior a manipulación de sustancias químicas',
   'Posterior a trauma, golpe o caída en el lugar de trabajo'],
  'Incapacidad o dificultad para hablar ': ['Ninguno de los anteriores',
   'En tu trabajo tuviste contacto por inhalación, ingesta o manipulación de insumos químicos (ej: pesticidas, disolventes) ',
   'Asociado a trauma, golpe o caída en el trabajo'],
  'Pérdida de la memoria': ['Ninguno de los anteriores',
   'Asociado a trauma, golpe o caída en el trabajo',
   'El deterioro de la memoria fue repentino y severo (no sabe quién es, dónde vive o la fecha)'],
  'Tienen convulsiones': ['Sin modificador'],
  'Temblor o movimientos raros en la cara o extremidades': ['Ninguno de los anteriores',
   'En tu trabajo tuviste contacto por inhalación, ingesta o manipulación de insumos químicos (ej: pesticidas, disolventes) ',
   'Asociado a trauma, golpe o caída en el trabajo'],
  'Alteraciones en el sueño': ['Ninguno de los anteriores',
   'Tienes antecedentes de depresión o ansiedad',
   'Posterior a un evento traumático o accidente en tu lugar de trabajo']},
 'Oídos': {'Pito en oídos': ['Ninguno de los anteriores',
   'Luego de exposición a un sonido muy fuerte',
   'El síntoma fue producto de un trauma en tu lugar de trabajo',
   'Asociado a vértigo por trabajo en alturas, acuático o vibración',
   'Asociado a uso constante de audífonos en el lugar de trabajo',
   'Asociado a dolor, sangrado o disminución de la audición'],
  'Dolor de oído': ['Ninguno de los anteriores',
   'Luego de exposición a un sonido muy fuerte',
   'El síntoma fue producto de un trauma en tu lugar de trabajo',
   'Asociado a cambios de presión en tu lugar de trabajo',
   'Asociado a uso constante de audífonos o tapones en el lugar de trabajo',
   'Asociado a sangrado, secreción o disminución de la audición'],
  'Sensación de oído tapado ': ['Ninguno de los anteriores',
   'Asociado a cuerpo extraño',
   'Asociado a uso constante de audífonos o tapones en el lugar de trabajo',
   'Asociado a cambios de presión o inmersión en tu lugar de trabajo'],
  'Pérdida o disminución de audición': ['Ninguno de los anteriores',
   'Luego de exposición a un sonido muy fuerte',
   'Asociado a trauma, explosión, golpe o caída en el trabajo',
   'Asociado a cambios de presión en tu lugar de trabajo',
   'Asociado a uso constante de audífonos o tapones en el lugar de trabajo',
   'Tengo diagnóstico de hipoacusia y requiero control'],
  'Cuerpo extraño en oído': ['Sin modificador'],
  'Secreción por el oído': ['Ninguno de los anteriores',
   'Asociado a uso constante de audífonos o tapones en el lugar de trabajo',
   'Asociado a trauma, explosión, golpe o caída en el trabajo',
   'Posterior a cirugía o procedimiento reciente en cabeza',
   'Posterior a cuerpo extraño',
   'Asociado a cambios de presión o inmersión en tu lugar de trabajo',
   'Asociado a contacto directo de alguna sustancia en el oido en tu lugar de trabajo'],
  'Quemaduras (por calor, vapor, eléctricas o químicas).': ['Sin modificador'],
  'Sangrado por oído el oído': ['Ninguno de los anteriores',
   'Asociado a trauma, explosión, golpe o caída en el trabajo',
   'Asociado a cambios de presión o inmersión en tu lugar de trabajo',
   'Posterior a cirugía o procedimiento reciente en cabeza',
   'Asociado a cuerpo extraño'],
  'Golpe con acumulación de sangre (hematoma) en la oreja': ['Sin modificador'],
  'Tengo ampollas en los oídos': ['Ninguno de los anteriores',
   'Asociado a quemadura por vapor, líquido, fuego o chispa',
   'Posterior a quemadura por vapor, líquido, fuego o chispa']},
 'Oftalmología': {'Trauma severo o penetrante en ojo': ['Sin modificador'],
  'Herida en ojo o en párpado': ['Sin modificador'],
  'Lagrimeo o secreción constante': ['Ninguno de los anteriores',
   'Asociado a exposición de sustancias irritantes en tu sitio de trabajo',
   'Posterior a cirugía en ojos o párpados por accidente de trabajo',
   'Asociado a contacto directo de alguna sustancia en el ojo en tu lugar de trabajo'],
  'Visión borrosa': ['Ninguno de los anteriores',
   'Asociado a trauma, explosión, golpe o caída en el trabajo',
   'Asociado a contacto directo de alguna sustancia en el ojo en tu lugar de trabajo',
   'Asociado a la exposición prolongada de pantallas en horario laboral',
   'Asociado a quemadura por vapor, líquido, fuego o chispa'],
  'Cuerpo extraño en ojo': ['Ninguno de los anteriores',
   'Asociado a irritación, dolor, sangrado o secreción en el ojo',
   'Pérdida o disminución de la visión'],
  'Ojo rojo': ['Ninguno de los anteriores',
   'Asociado a exposición de sustancias irritantes en tu sitio de trabajo',
   'Asociado a trauma, explosión, golpe o caída en el trabajo',
   'Asociado a contacto directo de alguna sustancia en el ojo en tu lugar de trabajo',
   'Asociado a cambios de presión en el lugar de trabajo',
   'Asociado a quemadura por vapor, líquido, fuego o chispa'],
  'Pérdida total de la visión (ceguera)': ['Ninguno de los anteriores',
   'Asociado a trauma, explosión, golpe o caída en el trabajo',
   'Asociado a contacto directo de alguna sustancia en el ojo en tu lugar de trabajo',
   'Asociado a quemadura por vapor, líquido, fuego o chispa',
   'Posterior a cirugía o procedimiento reciente en cabeza',
   'Tienes diagnosticado toxoplasmosis como enfermedad laboral'],
  'Disminución de la visión': ['Ninguno de los anteriores',
   'Asociado a trauma, explosión, golpe o caída en el trabajo',
   'Asociado a contacto directo de alguna sustancia en el ojo en tu lugar de trabajo',
   'Asociado a quemadura por vapor, líquido, fuego o chispa',
   'Posterior a cirugía o procedimiento reciente en cabeza',
   'Tienes diagnosticado toxoplasmosis como enfermedad laboral'],
  'Dolor en el ojo': ['Ninguno de los anteriores',
   'Asociado a dolor de cabeza secundario a trauma, cirugía o procedimiento médico',
   'Asociado a trauma, explosión, golpe o caída en el trabajo',
   'Asociado a contacto directo de alguna sustancia en el ojo en tu lugar de trabajo',
   'Asociado a quemadura por vapor, líquido, fuego o chispa',
   'Posterior a cirugía o procedimiento reciente en cabeza',
   'Tienes diagnóstico de glaucoma tóxico'],
  'Requiero control de mi enfermedad ocular': ['Sin modificador']},
 'Muscular o articular': {'Dolor de espalda': ['Ninguno de los anteriores',
   'Tengo dolor crónico pero aumentó de forma repentina',
   'Adormecimiento u hormigueo en las piernas de inicio reciente',
   'Asociado a trauma, explosión, movimiento brusco, golpe o caída en el trabajo',
   'El dolor se presentó de forma repentina después de levantar objetos pesados',
   'Se relacionó con el trauma pero viene aumentando en intensidad',
   'Se relacionó con el trauma pero es igual o ha disminuido en intensidad',
   'Incapacidad o dificultad para orinar o defecar',
   'Adormecimiento u hormigueo en la zona glútea o perianal',
   'Asociado a disminución de la fuerza muscular en extremidades',
   'Posterior a procedimiento o cirugía a causa de un accidente de trabajo o enfermedad laboral'],
  'Dolor de cuello': ['Ninguno de los anteriores',
   'Asociado a trauma, accidente, movimiento brusco, golpe o caída en el trabajo',
   'Tengo dolor crónico pero aumentó de forma repentina',
   'Adormecimiento, hormigueo o disminución de la fuerza en brazos o manos',
   'El dolor se presentó de forma repentina después de levantar objetos pesados',
   'Se relacionó con el trauma pero viene aumentando en intensidad',
   'Se relacionó con el trauma pero es igual o ha disminuido en intensidad',
   'Posterior a procedimiento o cirugía a causa de un accidente de trabajo o enfermedad laboral'],
  'Dolor en la rodilla': ['Ninguno de los anteriores',
   'Calor, enrojecimiento o hinchazón de la rodilla luego de un trauma en el lugar de trabajo',
   'Asociado a accidente, movimiento brusco, golpe o caída en el trabajo',
   'Posterior a procedimiento o cirugía a causa de un accidente de trabajo o enfermedad laboral',
   'El dolor se presentó de forma repentina después de levantar objetos pesados',
   'Asociado a bloqueo en la rodilla con limitación para caminar',
   'Tengo dolor crónico pero aumentó de forma repentina',
   'Se relacionó con el trauma pero viene aumentando en intensidad',
   'Se relacionó con el trauma pero es igual o ha disminuido en intensidad'],
  'Dolor en el hombro': ['Ninguno de los anteriores',
   'Asociado a accidente, trauma, movimiento brusco, golpe o caída en el trabajo',
   'Posterior a procedimiento o cirugía a causa de un accidente de trabajo o enfermedad laboral',
   'Se relacionó con el trauma pero viene aumentando en intensidad',
   'Se relacionó con el trauma pero es igual o ha disminuido en intensidad',
   'El dolor se presentó de forma repentina después de levantar objetos pesados',
   'El dolor se asocia con movimientos a repetición',
   'Tengo dolor crónico pero aumentó de forma repentina'],
  'Dolor en el tobillo o pie': ['Ninguno de los anteriores',
   'Calor, enrojecimiento o hinchazón en el tobillo o pie luego de un trauma en el lugar de trabajo',
   'Asociado a accidente, movimiento brusco, golpe o caída en el trabajo',
   'Posterior a procedimiento o cirugía a causa de un accidente de trabajo o enfermedad laboral',
   'El dolor se presentó de forma repentina después de torcedura ("me doblé el tobillo") del tobillo',
   'Tengo dolor crónico pero aumentó de forma repentina',
   'Se relacionó con el trauma pero viene aumentando en intensidad',
   'Se relacionó con el trauma pero es igual o ha disminuido en intensidad',
   'Asociado a trauma, golpe o contusión en un dedo o la uña'],
  'Dolor de cadera': ['Ninguno de los anteriores',
   'Asociado a accidente, trauma, movimiento brusco, golpe o caída en el trabajo',
   'Posterior a procedimiento o cirugía a causa de un accidente de trabajo o enfermedad laboral',
   'Se relacionó con el trauma pero viene aumentando en intensidad',
   'Se relacionó con el trauma pero es igual o ha disminuido en intensidad',
   'El dolor se presentó de forma repentina después de levantar objetos pesados',
   'Tengo dolor crónico pero aumentó de forma repentina',
   'Asociado a limitación para caminar',
   'Adormecimiento, hormigueo o disminución de la fuerza en extremidades',
   'El dolor es secundario a una enfermedad laboral en cadera y empeora con el movimiento'],
  'Dolor en mano o muñeca': ['Ninguno de los anteriores',
   'Asociado a accidente, trauma, movimiento brusco, golpe o caída en el trabajo',
   'Posterior a procedimiento o cirugía a causa de un accidente de trabajo o enfermedad laboral',
   'Se relacionó con el trauma pero viene aumentando en intensidad',
   'Se relacionó con el trauma pero es igual o ha disminuido en intensidad',
   'El dolor se presentó de forma repentina después de levantar objetos pesados',
   'Tengo dolor crónico pero aumentó de forma repentina',
   'Adormecimiento, hormigueo o disminución de la fuerza de la mano',
   'El dolor se asocia con movimientos a repetición',
   'Asociado a trauma, golpe o contusión en un dedo o la uña',
   'El dolor se presentó de forma repentina después de torcedura ("me doblé la mano o muñeca") '],
  'Dolor en el codo': ['Ninguno de los anteriores',
   'Asociado a accidente, trauma, movimiento brusco, golpe o caída en el trabajo',
   'Posterior a procedimiento o cirugía a causa de un accidente de trabajo o enfermedad laboral',
   'Se relacionó con el trauma pero viene aumentando en intensidad',
   'Se relacionó con el trauma pero es igual o ha disminuido en intensidad',
   'El dolor se presentó de forma repentina después de levantar objetos pesados',
   'Tengo dolor crónico pero aumentó de forma repentina',
   'Adormecimiento, hormigueo o disminución de la fuerza en extremidades',
   'El dolor se asocia con movimientos a repetición'],
  'Dolor en extremidades': ['Ninguno de los anteriores',
   'Hinchazón, enrojecimiento, calor o dolor en una de las extremidades posterior a cirugía o inmovilización por accidente de trabajo o enfermedad laboral',
   'Hinchazón, enrojecimiento, calor o dolor en una de las extremidades posterior a trauma o quietud prolongada',
   'Asociado a extremidad fría, morada o azul o sensación de hormigueo, posterior a trauma, cirugía o procedimiento']},
 'Piel, uñas, cabello, pestañas': {'Alergia, brote o erupción en la piel': ['Ninguno de los anteriores',
   'Posterior a la manipulación de sustancias químicas o irritantes en el trabajo',
   'Tengo diagnóstico de dermatitis por causa laboral y requiero control',
   'Asociado con la ingesta de alimentos suministrados en el trabajo',
   'Las lesiones se deben a picadura de insecto o contacto con plantas en actividades relacionadas con el trabajo',
   'Relacionado con material quirúrgico, insumos, medicamentos tópicos u orales secundario a procedimiento o cirugía'],
  'Infección en piel': ['Ninguno de los anteriores',
   'Asociado a trauma o accidente en el lugar de trabajo',
   'Secundario a procedimiento o cirugía por accidente de trabajo o enfermedad laboral',
   'Posterior a la manipulación de sustancias químicas o irritantes en el trabajo',
   'Posterior a picadura de insecto o contacto con plantas en actividades relacionadas con el trabajo',
   'Asociado a fiebre, escalofrío, secreción de pus o sangrado por el sitio de la herida',
   'Las infecciones son recurrentes posterior a procedimiento o cirugía por accidente de trabajo o enfermedad laboral'],
  'Dolor o sensación de quemazón en la piel': ['Ninguno de los anteriores',
   'Secundario a trauma o amputación de alguna parte de cuerpo por accidente de trabajo',
   'El dolor no ha mejorado a pesar del uso de analgésicos',
   'Posterior a la manipulación de sustancias químicas o irritantes en el trabajo',
   'Posterior a picadura de insecto o contacto con plantas en actividades relacionadas con el trabajo'],
  'Quemaduras (por calor, exposición al sol, eléctricas o químicas).': ['Ninguno de los anteriores',
   'Raspón, laceración, abrasión o peladura en la piel secundario a accidente, trauma o golpe en el lugar de trabajo',
   'Posterior a la manipulación de sustancias químicas o irritantes en el trabajo',

In [17]:
get_categorias()

['Boca, garganta y cuello',
 'Caídas, accidentes, traumas',
 'Ginecológico',
 'Génitourinario ',
 'Muscular o articular',
 'Nariz',
 'Neurológico o cabeza',
 'Oftalmología',
 'Oídos',
 'Piel, uñas, cabello, pestañas',
 'Respiratorio',
 'Riesgo biológico',
 'Salud mental',
 'Vascular',
 'Violencia']

In [18]:
get_sintomas(get_categorias()[0])

['Dificultad para tragar (ej: se me atora la comida)',
 'Golpe o trauma en la boca']

In [19]:
get_modificadores(get_categorias()[0], get_sintomas(get_categorias()[0])[0])

['Asociado a trauma o quemadura en el lugar de trabajo']

In [20]:
len(get_all_sintomas_flat())

92

## Combinacion de triage-categoria-especialidad

In [2]:
df_triage = build_triage_combinations_from_excel("../data/triage_sintomas.xlsx")

In [3]:
df_triage

,categoria,sintoma,modificador,nivel_triage,modalidad,especialidad
0,boca_garganta_y_cuello,golpe_o_trauma_en_la_boca,ninguno_de_los_anteriores,T4,presencial,odontologia
1,boca_garganta_y_cuello,golpe_o_trauma_en_la_boca,lesion_de_encia_o_mucosas_orales,T4,presencial,general
2,boca_garganta_y_cuello,golpe_o_trauma_en_la_boca,cambio_de_color_evidente_en_un_diente_luego_de...,T3,urgencias,odontologia
3,boca_garganta_y_cuello,golpe_o_trauma_en_la_boca,asociado_a_dolor_y_deformidad_en_boca_o_mandibula,T3,urgencias,general
4,boca_garganta_y_cuello,golpe_o_trauma_en_la_boca,fractura_evidente_del_tejido_dental,T3,urgencias,odontologia
...,...,...,...,...,...,...
378,nan,nan,nan,TRIAGE_2,nan,general
379,nan,nan,nan,TRAIGE_3,nan,general
380,nan,nan,nan,TRAIGE_4,nan,general
381,nan,nan,nan,TRIAGE_5,nan,general
382,nan,nan,,NAN,nan,general

# Pruebas data prestadores

In [4]:
df_prestadores = pd.read_excel("../data/prestadores_mapa.xlsx")
df_prestadores_urg = pd.read_excel("../data/prestadores_urg.xlsx")

In [5]:
# Limpiar datos de prestadores usando la función reutilizable
prestadores_clean = clean_providers_data(df_prestadores)

✓ 44263 registros iniciales cargados
✓ 39820 registros después de eliminar prestadores no válidos
✓ 38774 registros después de filtrar direccionamiento != 9
✓ 31964 registros después de eliminar coordenadas inválidas
✓ 4852 registros después de filtrar por servicios útiles

In [ ]:
# Limpiar datos de prestadores urgencias
prestadores_urg_clean = clean_providers_data(df_prestadores_urg)

✓ 1511 registros iniciales cargados
✓ 1511 registros después de eliminar prestadores no válidos
✓ 1426 registros después de filtrar direccionamiento != 9
✓ 1421 registros después de eliminar coordenadas inválidas
✓ 1412 registros después de filtrar por servicios útiles

In [7]:
# Combinar la data de prestadores con prestadores urgencias
# Para cada sucursal única en prestadores_urg_clean, actualizar direccion, lat y lng en prestadores_clean
prestadores_final = merge_provider_locations(prestadores_clean, prestadores_urg_clean)

📍 Encontradas 874 combinaciones únicas (sucursal, departamento, municipio) en datos de urgencias
✓ Actualizados 4266 registros de 820 combinaciones únicas
✓ 4852 registros totales en dataset final

✓ Actualizados 4266 registros de 820 combinaciones únicas
✓ 4852 registros totales en dataset final

In [7]:
prestadores_final["servicio_prestador"].value_counts()

servicio_prestador
urgencias_medico_general                    654
consulta_odontologica                       625
consulta_psicologo_y_terapia_psicologica    416
consulta_ortopedista                        402
consulta_no_programada                      319
consulta_medicina_interna                   287
consulta_cirujano_general                   263
consulta_otorrinolaringologia               216
consulta_urologia                           215
cirugia_urologia                            199
consulta_oftalmologia                       192
cirugia_otorrinolaringologia                189
cirugia_oftalmologia                        188
urgencias_ortopedista                       175
consulta_y_procedimientos_dermatologia      155
consulta_neurologo                           98
urgencias_riesgo_biologico                   91
consulta_medicina_fisica_y_de_deporte_l      37
consulta_prioritaria_de_oftalmologia_l       35
consulta_medicin_interna_telemedicina_l      35
urgencias_odontologia_l                      22
urgencias_oftalmologia                       22
consulta_prioritaria_odontologia_l           13
consulta_dermatologia_telemedicina_l          4
Name: count, dtype: int64

In [8]:
prestadores_final.head()

,prestador,sucursal,departamento,municipio,direccion,lat,lng,servicio_prestador,prioridad_recomendacion,horario,telefono_fijo,telefono_celular
1459,ANDERSON BERRIO HERRERA,ANDERSON BERRIO HERRERA,Bolivar,Cartagena De Indias,MANGA CR 24#26-73,10.410363,-75.534914,consulta_ortopedista,1,NaN,NaN,3108837365
1486,CASTAÑO CARDENAS VICTOR MANUEL,VICTOR MANUEL CASTAÑO CARDENAS,Risaralda,Pereira,CR 9ª 25-25 CLINICA LOS ROSAL,4.813518,-75.699665,consulta_ortopedista,2,NaN,(6)3243677,citas 3127499661
1513,IVAN LEONARDO DUQUE VERA - DUQUE VERA IVAN,IVAN LEONARDO DUQUE VERA,Caldas,Manizales,CR 25 49-46,5.062783,-75.499138,consulta_medicina_fisica_y_de_deporte_l,0,NaN,(6)8859535,3117481480 solo convenio
1540,GALLEGO URIBE JUAN CARLOS,JUAN CARLOS GALLEGO URIBE,Caldas,Manizales,CLIN LA PRESENTACION CONS 327,5.065287,-75.501584,consulta_ortopedista,1,LUNES VIERNES-8AM-5PM,(6)8782800,3243915393
1557,RODRIGO ALBERTO PENAGOS LOPEZ,RODRIGO ALBERTO PENAGOS,Atlantico,Barranquilla,CR 30 # 1-850 COSULTORIO 604,11.004108,-74.818323,consulta_ortopedista,2,NaN,(5)3737555,3043395030

In [13]:
prestadores_final.nunique()

prestador                   965
sucursal                   1105
departamento                 30
municipio                   543
direccion                  1104
lat                        1101
lng                        1101
servicio_prestador           24
prioridad_recomendacion       7
horario                     105
telefono_fijo               986
telefono_celular            615
dtype: int64

In [12]:
prestadores_final["sucursal"].value_counts()

sucursal
CLINICA MEDILASER                     25
CLINICA CARLOS ARDILA LULLE FOSCAL    22
CLINICA REINA CATALINA Y CIA LTDA     22
CARVAJAL LABORATORIOS IPS SAS         20
CLINICA CES                           19
                                      ..
CENTRO DE SALUD DE LENGUAZAQUE         1
CENTRO DE SALUD DE SUSA                1
CENTRO DE SALUD DE FUQUENE             1
PUESTO DE SALUD SAN PEDRO DE JAGUA     1
CERRO AZUL CENTRO MEDICO               1
Name: count, Length: 1105, dtype: int64

# Correspondencia triage-servicio

In [3]:
PATH_TRIAGE = "../data/triage_sintomas.xlsx"
PATH_PRESTADORES = "../data/prestadores_mapa.xlsx"
PATH_PRESTADORES_URG = "../data/prestadores_urg.xlsx"

# Construir combinaciones clínicas
df_triage = build_triage_combinations(PATH_TRIAGE)

# Cargar prestadores limpios
df_prestadores = pd.read_excel(PATH_PRESTADORES)
df_prestadores_urg = pd.read_excel(PATH_PRESTADORES_URG)
prestadores_urg_clean = clean_providers_data(df_prestadores_urg, verbose=False)
prestadores_clean = clean_providers_data(df_prestadores, verbose=False)
prestadores_final = merge_provider_locations(
    prestadores_clean, prestadores_urg_clean, verbose=False
)

2025-12-04 21:20:50.573 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

✓ Limpieza completada: 1412 registros de prestadores

✓ Limpieza completada: 4852 registros de prestadores

✓ Merge completado: 4266 registros actualizados de 820 combinaciones únicas

✓ Merge completado: 4266 registros actualizados de 820 combinaciones únicas

In [8]:
df_triage.sample(5)

,categoria,sintoma,modificador,nivel_triage,modalidad,especialidad
266,piel_unas_cabello_pestanas,infeccion_en_piel,asociado_a_fiebre_escalofrio_secrecion_de_pus_...,T3,urgencias,dermatologia
37,ginecologico,flujo_vaginal,ninguno_de_los_anteriores,T5,presencial,nan
124,oftalmologia,perdida_total_de_la_vision_ceguera,asociado_a_quemadura_por_vapor_liquido_fuego_o...,T2,urgencias,nan
227,muscular_o_articular,dolor_de_cadera,tengo_dolor_cronico_pero_aumento_de_forma_repe...,T4,presencial,cirugia_general
146,oidos,dolor_de_oido,asociado_a_sangrado_secrecion_o_disminucion_de...,T2,urgencias,nan

In [5]:
prestadores_final.sample(5)

,prestador,sucursal,departamento,municipio,direccion,lat,lng,servicio_prestador,prioridad_recomendacion,horario,telefono_fijo,telefono_celular
23778,CLINICA CHINITA,CLINICA CHINITA APARTADO,Antioquia,Apartado,KR 98 102 11,7.867500,-76.635139,urgencias_medico_general,3,NaN,(4)8156060,NaN
9517,E.S.E CENTRO DE SALUD CUCUNUBA,ESE CENTRO DE SALUD CUCUNUBA,Cundinamarca,Cucunuba,KR 4 4 61,5.249772,-73.767743,consulta_medicina_general,1,NaN,(1)8580128,NaN
34670,CLINICA CES,CLINICA CES,Antioquia,Medellin,CL 58 50 C 2,6.257389,-75.565690,urgencias_medico_general,1,NaN,(4)4440555,(4)3229303 CITAS
31101,FUNDACION SANTA FE DE BOGOTA,FUNDACION SANTA FE DE BOGOTA,Bogota D.C.,Bogota,CL 119 7 75,4.696177,-74.032935,consulta_y_procedimientos_dermatologia,0,24 HORAS,(1)6030303,CITAS ORTOPEDIA 2152090
25878,CLINICA CARRIAZO S.A.,CLINICA CARRIAZO S.A,Atlantico,Barranquilla,Calle 86 # 49C -58,11.005022,-74.820769,cirugia_oftalmologia,0,NaN,(5)3673992,NaN

In [6]:
df_correspondencia = build_triage_correspondence_table(
    path_triage=PATH_TRIAGE,
    path_prestadores=PATH_PRESTADORES,
    path_prestadores_urg=PATH_PRESTADORES_URG,
)

2025-12-04 21:20:51.522 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-04 21:20:51.523 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:51.523 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:51.554
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /opt/homebrew/Caskroom/miniconda/base/envs/maestria/lib/python3.13/site-packages/ipykernel_launcher.py [ARGUMENTS]
2025-12-04 21:20:51.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:51.555 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:51.555 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:51.554
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /opt/homebrew/Caskroom/miniconda/base/envs/maestria/lib/python3.13/site-packages/ipykernel_launcher.py [ARGUMENTS]
2025-12-04 21:20:51.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:51.555 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:51.555 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:51.579 No runtime found, using MemoryCacheStorageManager
2025-12-04 21:20:51.579 No runtime found, using MemoryCacheStorageManager
2025-12-04 21:20:52.059 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:52.061 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:52.063 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:52.059 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:52.061 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:20:52.063 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.

✓ Merge completado: 4266 registros actualizados de 820 combinaciones únicas

2025-12-04 21:21:00.621 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:21:00.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:21:00.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:21:00.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-04 21:21:00.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

102 correspondencias generadas.
            categoria nivel_triage modalidad_requerida especialidad_requerida  \
99   riesgo_biologico           T4          presencial                    nan
100  riesgo_biologico           T3           urgencias                    nan
101  riesgo_biologico           T5             virtual                    nan

              servicios_sugeridos   scores   tipo_coincidencia
99    [consulta_medicina_general]    [1.0]            fallback
100  [urgencias_riesgo_biologico]  [0.928]  ctg_semantic_match
101   [consulta_medicina_general]    [1.0]            fallback

In [9]:
df_correspondencia

,categoria,nivel_triage,modalidad_requerida,especialidad_requerida,servicios_sugeridos,scores,tipo_coincidencia
0,boca_garganta_y_cuello,T4,presencial,odontologia,"[consulta_odontologica, consulta_prioritaria_o...","[0.857, 0.78, 0.701]",semantic_match
1,boca_garganta_y_cuello,T4,presencial,nan,[consulta_medicina_general],[1.0],fallback
2,boca_garganta_y_cuello,T3,urgencias,odontologia,[urgencias_odontologia],[0.738],semantic_match
3,boca_garganta_y_cuello,T3,urgencias,nan,[urgencias_medico_general],[1.0],fallback
4,boca_garganta_y_cuello,T3,nan,nan,[urgencias_medico_general],[1.0],fallback
...,...,...,...,...,...,...,...
97,vascular,T2,urgencias,nan,[urgencias_medico_general],[1.0],fallback
98,riesgo_biologico,T2,urgencias,nan,[urgencias_riesgo_biologico],[0.928],ctg_semantic_match
99,riesgo_biologico,T4,presencial,nan,[consulta_medicina_general],[1.0],fallback
100,riesgo_biologico,T3,urgencias,nan,[urgencias_riesgo_biologico],[0.928],ctg_semantic_match
101,riesgo_biologico,T5,virtual,nan,[consulta_medicina_general],[1.0],fallback

In [ ]:
# with st.spinner("Generando correspondencias triage–servicios..."):
#     df_corr = build_correspondence_table_v3(
#         df_sintomas, df_prestadores, method="semantic", threshold=0.6, verbose=False
#     )